# Generated by Django 2.2.5 on 2019-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddaj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='oddaj.Category'),
        ),
    ]
